[project]
name = "memorymanager"
version = "0.0.1"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mypy>=1.17.0",
    "ruff>=0.12.5",
]

[mypy]
python_version = "3.13"
strict = true